set completeopt=menuone,noinsert,noselect
set expandtab
set guicursor=
set hidden
set ignorecase
set incsearch
set nobackup
set noerrorbells
"set nohlsearch
set noshowmode
set noswapfile
"set nowrap
set nu
set relativenumber
set scrolloff=8
set shiftwidth=4
set smartcase
set smartindent
set tabstop=4 softtabstop=4
set termguicolors
set undodir=~/.vim/undodir
set undofile
syntax on
